# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb2a4c5ee2cfc49432b4543552f16dd3dd803671e5d3fa667d856af97894ead95928cec1d4d17e058c26008bdcd821006bc77bd3d991e0ae3236d02a33f6586

test:
  secret_key_base: 532ca59df799a7cfcd169b746986157a5ce8b606c6095118b9bd4cf5a4f5765516fb1b3b10b449533da6b7cbcb9905850f2ce08f7c0c0bf1cd5cc539eb71a8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
